name: nodeseek鸡腿签到

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 16 * * *'  # 北京时间 00:00 (UTC+8)，对应UTC时间 16:00
  workflow_dispatch:

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v3
      
      - name: 配置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: 安装依赖包
        run: pip install curl_cffi requests

      - name: 运行签到脚本
        env:
          # 基本配置
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          NS_RANDOM: ${{ secrets.NS_RANDOM }}

          # 验证码服务配置
          SOLVER_TYPE: ${{ secrets.SOLVER_TYPE }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          CLIENTT_KEY: ${{ secrets.CLIENTT_KEY }}
          
          # 通知推送配置
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
        run: python nodeseek_sign.py
